#pragma once

enum trade_condition {
  regular_sale,
  acquisition,
  bunched_trade,
  cash_trade,
  distribution,
  placeholder_for_future_use,
  intermarket_sweep,
  bunched_sold_trades,
  price_variation_trade,
  odd_lot_trade,
  rule_155_trade = 11,
  sold_last,
  market_center_close_price,
  next_day,
  opened,
  prior_reference_price,
  market_center_open_price,
  seller,
  split_trade,
  form_t_preopen_and_postclose_market_trade,
  extended_trading_hours_sold_out_of_sequence,
  contingent_trade,
  average_price_trade,
  cross_trade,
  yellow_flag,
  sold_out_of_sequence,
  odd_lot_execution_for_nasdaq_last_sale,
  odd_lot_cross_trade,
  stopped_stock_regular_trade = 49,
  derivatively_priced = 52,
  reopening_prints,
  closing_prints,
  qualified_contingent_trade,
  placeholder_for_611_exempt,
  consolidated_late_price_per_listing_packet
};
